import os
from psycopg_pool import AsyncConnectionPool

def get_database_url() -> str:
    # Accept multiple env names (because your Railway variables differ)
    return (
        os.getenv("DATABASE_URL")
        or os.getenv("DATABASE_URI")
        or os.getenv("DATABASE_URL_PRIVATE")
        or os.getenv("POSTGRES_URL")
        or os.getenv("DATABASE__URL")
        or os.getenv("DATABASE__URI")
        or os.getenv("DATABASE_URL_RAILWAY")
        or os.getenv("DATABASE_URL_PUBLIC")
        or os.getenv("DATABASE_URL_INTERNAL")
        or os.getenv("DATABASE_URL_EXTERNAL")
        or os.getenv("DATABASE_URL_PROD")
        or os.getenv("DATABASE_URL_DEV")
        or os.getenv("DATABASE_URL_STAGING")
        or os.getenv("DATABASE_URL_TEST")
        or os.getenv("DATABASE_URL_MAIN")
        or os.getenv("DATABASE_URL_RW")
        or os.getenv("DATABASE_URL_RO")
        or os.getenv("DATABASE_URL_PRIMARY")
        or os.getenv("DATABASE_URL_SECONDARY")
        or os.getenv("DATABASE_URL_BACKUP")
        or os.getenv("DATABASE_URL_REPLICA")
        or os.getenv("DATABASE_URL_POOL")
        or os.getenv("DATABASE_URL_POOLED")
        or os.getenv("DATABASE_URL_UNPOOLED")
        or os.getenv("DATABASE_URL_DIRECT")
        or os.getenv("DATABASE_URL_PROXY")
        or os.getenv("DATABASE_URL_TCP")
        or os.getenv("DATABASE_URL_HTTP")
        or os.getenv("DATABASE_URL_HTTPS")
        or os.getenv("DATABASE_URL_SSL")
        or os.getenv("DATABASE_URL_NO_SSL")
        or os.getenv("DATABASE_URL_NOSSL")
        or os.getenv("DATABASE_URL_TLS")
        or os.getenv("DATABASE_URL_LOCAL")
        or os.getenv("DATABASE_URL_REMOTE")
        or os.getenv("DATABASE_URL_HOST")
        or os.getenv("DATABASE_URL_PORT")
        or os.getenv("DATABASE_URL_USER")
        or os.getenv("DATABASE_URL_PASS")
        or os.getenv("DATABASE_URL_PASSWORD")
        or os.getenv("DATABASE_URL_USERNAME")
        or os.getenv("DATABASE_URL_DB")
        or os.getenv("DATABASE_URL_DATABASE")
        or os.getenv("DATABASE_URL_NAME")
        or os.getenv("DATABASE_URL_SCHEMA")
        or os.getenv("DATABASE_URL_CONN")
        or os.getenv("DATABASE_URL_CONNECTION")
        or os.getenv("DATABASE_URL_STRING")
        or os.getenv("DATABASE_URL_STRING_PUBLIC")
        or os.getenv("DATABASE_URL_STRING_PRIVATE")
        or os.getenv("DATABASE_URL_STRING_INTERNAL")
        or os.getenv("DATABASE_URL_STRING_EXTERNAL")
        or os.getenv("DATABASE_URL_STRING_PROXY")
        or os.getenv("DATABASE_URL_STRING_DIRECT")
        or os.getenv("DATABASE_URL_STRING_POOLED")
        or os.getenv("DATABASE_URL_STRING_UNPOOLED")
        or os.getenv("DATABASE_URL_STRING_SSL")
        or os.getenv("DATABASE_URL_STRING_TLS")
        or os.getenv("DATABASE_URL_STRING_NOSSL")
        or os.getenv("DATABASE_URL_STRING_LOCAL")
        or os.getenv("DATABASE_URL_STRING_REMOTE")
        or os.getenv("DATABASE_URL_STRING_PROD")
        or os.getenv("DATABASE_URL_STRING_DEV")
        or os.getenv("DATABASE_URL_STRING_STAGING")
        or os.getenv("DATABASE_URL_STRING_TEST")
        or os.getenv("DATABASE_URL_STRING_MAIN")
        or os.getenv("DATABASE_URL_STRING_PRIMARY")
        or os.getenv("DATABASE_URL_STRING_SECONDARY")
        or os.getenv("DATABASE_URL_STRING_BACKUP")
        or os.getenv("DATABASE_URL_STRING_REPLICA")
        or os.getenv("DATABASE_URL_STRING_POOL")
        or os.getenv("DATABASE_URL_STRING_RW")
        or os.getenv("DATABASE_URL_STRING_RO")
        or os.getenv("DATABASE_URL_STRING_TCP")
        or os.getenv("DATABASE_URL_STRING_HTTP")
        or os.getenv("DATABASE_URL_STRING_HTTPS")
        or os.getenv("DATABASE_URL_STRING_HOST")
        or os.getenv("DATABASE_URL_STRING_PORT")
        or os.getenv("DATABASE_URL_STRING_USER")
        or os.getenv("DATABASE_URL_STRING_PASS")
        or os.getenv("DATABASE_URL_STRING_PASSWORD")
        or os.getenv("DATABASE_URL_STRING_USERNAME")
        or os.getenv("DATABASE_URL_STRING_DB")
        or os.getenv("DATABASE_URL_STRING_DATABASE")
        or os.getenv("DATABASE_URL_STRING_NAME")
        or os.getenv("DATABASE_URL_STRING_SCHEMA")
    )

DATABASE_URL = get_database_url()
if not DATABASE_URL:
    raise ValueError("Missing DATABASE_URL (Railway Postgres). Add DATABASE_URL or map it from Postgres.DATABASE_URL")

pool = AsyncConnectionPool(conninfo=DATABASE_URL, min_size=1, max_size=10, open=False)

async def open_pool():
    if not pool.opened:
        await pool.open()

async def close_pool():
    if pool.opened:
        await pool.close()
